# Generated by Django 6.0.2 on 2026-04-15 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCau',
            fields=[
                ('MaYeuCau', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã yêu cầu phải bắt đầu bằng 'MYC' followed by digits (ví dụ: MYC001).", regex='^MYC\\d+$')], verbose_name='Mã yêu cầu')),
                ('LoaiYC', models.CharField(choices=[('Đăng ký ca', 'Đăng ký ca'), ('Nghỉ phép', 'Nghỉ phép')], max_length=100, verbose_name='Loại yêu cầu')),
                ('NgayBD', models.DateField(verbose_name='Ngày bắt đầu')),
                ('NgayKT', models.DateField(verbose_name='Ngày kết thúc')),
                ('CaLam', models.CharField(choices=[('Ca sáng (6h-12h)', 'Ca sáng (6h-12h)'), ('Ca chiều (12h-17h)', 'Ca chiều (12h-17h)'), ('Ca tối (17h-22h)', 'Ca tối (17h-22h)')], max_length=50, verbose_name='Ca làm việc')),
                ('LyDo', models.TextField(blank=True, null=True, verbose_name='Lý do')),
                ('NgayDK', models.DateField(verbose_name='Ngày đăng ký')),
                ('TrangThai', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Đã từ chối', 'Đã từ chối')], max_length=50, verbose_name='Trạng thái')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Yêu cầu',
                'verbose_name_plural': 'Danh sách yêu cầu',
            },
        ),
    ]
