# Generated by Django 6.0.2 on 2026-04-15 12:03

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employee', '0001_initial'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('MaBaoCao', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã báo cáo phải bắt đầu bằng 'BC' followed by digits (ví dụ: BC001).", regex='^BC\\d+$')], verbose_name='Mã báo cáo')),
                ('TenBaoCao', models.CharField(choices=[('Báo cáo Lương', 'Báo cáo Lương'), ('Báo cáo Chấm công', 'Báo cáo Chấm công')], max_length=255, verbose_name='Tên báo cáo')),
                ('ThangNam', models.CharField(max_length=20, verbose_name='Tháng năm')),
                ('ChucVu', models.CharField(choices=[('Thu ngân', 'Thu ngân'), ('Quản lý', 'Quản lý'), ('Pha chế', 'Pha chế'), ('Phục vụ', 'Phục vụ'), ('Giữ xe', 'Giữ xe')], max_length=50, verbose_name='Chức vụ')),
                ('TrangThai', models.CharField(choices=[('Đang làm', 'Đang làm'), ('Đã Nghỉ', 'Đã Nghỉ')], max_length=50, verbose_name='Trạng thái')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Danh sách báo cáo',
            },
        ),
        migrations.CreateModel(
            name='BaoCao_CT',
            fields=[
                ('MaBaoCaoCT', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã báo cáo chi tiết phải bắt đầu bằng 'BCCT' followed by digits (ví dụ: BCCT001).", regex='^BCCT\\d+$')], verbose_name='Mã báo cáo chi tiết')),
                ('TenBaoCao', models.CharField(max_length=255, verbose_name='Tên báo cáo')),
                ('Thang', models.IntegerField(verbose_name='Tháng')),
                ('NgayTao', models.DateField(default=datetime.date.today, verbose_name='Ngày tạo')),
                ('TongGioLam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng giờ làm')),
                ('NgayNghiPhep', models.IntegerField(verbose_name='Ngày nghỉ phép')),
                ('NgayKhongPhep', models.IntegerField(verbose_name='Ngày không phép')),
                ('MaBaoCao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.baocao', verbose_name='Mã báo cáo')),
                ('MaChamCong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.chamcong', verbose_name='Mã chấm công')),
                ('MaLuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.bangluong', verbose_name='Mã lương')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chi tiết báo cáo',
                'verbose_name_plural': 'Danh sách chi tiết báo cáo',
            },
        ),
    ]
