# Generated by Django 6.0.2 on 2026-04-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baocao',
            name='ThangNam',
        ),
        migrations.RemoveField(
            model_name='baocao_ct',
            name='Thang',
        ),
    ]
