# Generated by Django 6.0.2 on 2026-04-15 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_baocao_thangnam_remove_baocao_ct_thang'),
    ]

    operations = [
        migrations.AddField(
            model_name='baocao',
            name='ThangNam',
            field=models.DateField(default=datetime.date.today, verbose_name='Tháng năm'),
        ),
        migrations.AddField(
            model_name='baocao_ct',
            name='Thang',
            field=models.DateField(default=datetime.date.today, verbose_name='Tháng'),
        ),
    ]
