# Generated by Django 6.0.2 on 2026-04-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_baocao_thangnam_baocao_ct_thang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baocao_ct',
            name='TenBaoCao',
            field=models.CharField(choices=[('Báo cáo Lương', 'Báo cáo Lương'), ('Báo cáo Chấm công', 'Báo cáo Chấm công')], max_length=255, verbose_name='Tên báo cáo'),
        ),
    ]
