# Generated by Django 6.0.3 on 2026-04-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('report', '0004_alter_baocao_ct_tenbaocao'),
        ('salary', '0004_alter_bangluong_sogiolam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baocao_ct',
            name='MaChamCong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.chamcong', verbose_name='Mã chấm công'),
        ),
        migrations.AlterField(
            model_name='baocao_ct',
            name='MaLuong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.bangluong', verbose_name='Mã lương'),
        ),
    ]
