# Generated by Django 6.0.2 on 2026-04-15 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangLuong',
            fields=[
                ('MaLuong', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã lương phải bắt đầu bằng 'BL' followed by digits (ví dụ: BL001).", regex='^BL\\d+$')], verbose_name='Mã lương')),
                ('ThoiGian', models.IntegerField(verbose_name='Tháng/Năm')),
                ('LuongCoBan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lương cơ bản')),
                ('LuongTheoGio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lương theo giờ')),
                ('SoGioLam', models.IntegerField(verbose_name='Số giờ làm')),
                ('TongThuong', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng thưởng')),
                ('TongPhat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng phạt')),
                ('TongThucLanh', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng thực lãnh')),
                ('TrangThai', models.CharField(choices=[('Đang chờ duyệt', 'Đang chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Đã từ chối', 'Đã từ chối')], max_length=50, verbose_name='Trạng thái')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Danh sách bảng lương',
            },
        ),
    ]
