# Generated by Django 6.0.2 on 2026-04-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangluong',
            name='ThoiGian',
        ),
    ]
