# Generated by Django 6.0.2 on 2026-04-15 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_remove_bangluong_thoigian'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangluong',
            name='ThoiGian',
            field=models.DateField(default=datetime.date.today, verbose_name='Tháng/Năm'),
        ),
    ]
