# Generated by Django 6.0.4 on 2026-04-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_bangluong_thoigian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangluong',
            name='SoGioLam',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Số giờ làm'),
        ),
    ]
