# Generated by Django 6.0.2 on 2026-04-15 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('MaChamCong', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã chấm công phải bắt đầu bằng 'CC' followed by digits (ví dụ: CC001).", regex='^CC\\d+$')], verbose_name='Mã chấm công')),
                ('GioVao', models.TimeField(verbose_name='Giờ vào')),
                ('GioRa', models.TimeField(verbose_name='Giờ ra')),
                ('SoGioLam', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Số giờ làm')),
                ('TrangThai', models.CharField(choices=[('Đúng giờ', 'Đúng giờ'), ('Trễ', 'Trễ'), ('Vắng', 'Vắng')], max_length=50, verbose_name='Trạng thái')),
                ('GhiChu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('MaLich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lichlamviec', verbose_name='Lịch làm việc')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Danh sách chấm công',
            },
        ),
    ]
