# Generated by Django 6.0.2 on 2026-04-15 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('MaLich', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã lịch phải bắt đầu bằng 'MLLV' followed by digits (ví dụ: MLLV001).", regex='^MLLV\\d+$')], verbose_name='Mã lịch')),
                ('NgayLam', models.DateField(verbose_name='Ngày làm')),
                ('CaLam', models.CharField(choices=[('Ca sáng (6h-12h)', 'Ca sáng (6h-12h)'), ('Ca chiều (12h-17h)', 'Ca chiều (12h-17h)'), ('Ca tối (17h-22h)', 'Ca tối (17h-22h)')], max_length=50, verbose_name='Ca làm')),
                ('GhiChu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('TrangThai', models.CharField(choices=[('Chưa gửi', 'Chưa gửi'), ('Đã gửi', 'Đã gửi')], max_length=50, verbose_name='Trạng thái')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Danh sách lịch làm việc',
            },
        ),
    ]
