# Generated by Django 6.0.2 on 2026-04-17 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichlamviec',
            name='GioBatDau',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu'),
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='GioKetThuc',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='CaLam',
            field=models.CharField(blank=True, choices=[('Ca sáng (6h-12h)', 'Ca sáng (6h-12h)'), ('Ca chiều (12h-17h)', 'Ca chiều (12h-17h)'), ('Ca tối (17h-22h)', 'Ca tối (17h-22h)')], max_length=50, null=True, verbose_name='Ca làm'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='MaLich',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã lịch phải bắt đầu bằng 'MLLV' followed by digits (ví dụ: MLLV001).", regex='^MLLV\\d+$')], verbose_name='Mã lịch'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chưa gửi', 'Chưa gửi'), ('Đã gửi', 'Đã gửi')], default='Chưa gửi', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
