# Generated by Django 6.0.4 on 2026-04-18 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_lichlamviec_giobatdau_lichlamviec_gioketthuc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichlamviec',
            name='CaLam',
            field=models.CharField(blank=True, choices=[('Ca sáng', 'Ca sáng'), ('Ca chiều', 'Ca chiều'), ('Ca tối', 'Ca tối')], max_length=50, null=True, verbose_name='Ca làm'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='MaLich',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã lịch phải bắt đầu bằng 'MLLV' followed by digits (ví dụ: MLLV000001).", regex='^MLLV\\d+$')], verbose_name='Mã lịch'),
        ),
    ]
