# Generated by Django 6.0.2 on 2026-04-15 12:03

import django.core.validators
import pages.employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNhanVien', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã nhân viên phải bắt đầu bằng 'NV' followed by digits (ví dụ: NV001).", regex='^NV\\d+$')], verbose_name='Mã nhân viên')),
                ('HoTen', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Họ tên chỉ được chứa chữ cái và khoảng trắng.', regex='^[a-zA-ZÀ-ỹ\\s]+$')], verbose_name='Họ tên')),
                ('GioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('Ngaysinh', models.DateField(validators=[pages.employee.models.validate_min_age], verbose_name='Ngày sinh')),
                ('TaiKhoanNH', models.CharField(max_length=100, verbose_name='Tài khoản ngân hàng')),
                ('SoDienThoai', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có 10 chữ số và bắt đầu bằng số 0.', regex='^0\\d{9}$')], verbose_name='Số điện thoại')),
                ('CCCD', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='CCCD phải có đúng 12 chữ số.', regex='^\\d{12}$')], verbose_name='CCCD/CMND')),
                ('DiaChiLV', models.CharField(max_length=255, verbose_name='Địa chỉ làm việc')),
                ('DiaChi', models.CharField(max_length=255, verbose_name='Địa chỉ thường trú')),
                ('ChucVu', models.CharField(choices=[('Thu ngân', 'Thu ngân'), ('Quản lý', 'Quản lý'), ('Pha chế', 'Pha chế'), ('Phục vụ', 'Phục vụ'), ('Giữ xe', 'Giữ xe')], max_length=50, verbose_name='Chức vụ')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
            },
        ),
    ]
