# Generated by Django 6.0.3 on 2026-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='HinhAnh',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Hình ảnh'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='TrangThai',
            field=models.CharField(choices=[('Đang làm việc', 'Đang làm việc'), ('Ngừng hoạt động', 'Ngừng hoạt động')], default='Đang làm việc', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
