# Generated by Django 6.0.3 on 2026-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_nhanvien_hinhanh_nhanvien_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Hình ảnh'),
        ),
    ]
