# Generated by Django 6.0.3 on 2026-04-16 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_nhanvien_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='CCCD',
            field=models.CharField(error_messages={'unique': 'Số CCCD này đã tồn tại trong hệ thống.'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='CCCD phải có đúng 12 chữ số.', regex='^\\d{12}$')], verbose_name='CCCD/CMND'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='SoDienThoai',
            field=models.CharField(error_messages={'unique': 'Số điện thoại này đã tồn tại trong hệ thống.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có 10 chữ số và bắt đầu bằng số 0.', regex='^0\\d{9}$')], verbose_name='Số điện thoại'),
        ),
    ]
