# Generated by Django 6.0.4 on 2026-04-18 04:40

import django.core.validators
import pages.employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_nhanvien_cccd_alter_nhanvien_sodienthoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='CCCD',
            field=models.CharField(error_messages={'required': 'CCCD không được để trống. Vui lòng nhập thông tin', 'unique': 'Số CCCD này đã tồn tại trong hệ thống.'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='CCCD phải có đúng 12 chữ số.', regex='^\\d{12}$')], verbose_name='CCCD/CMND'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ChucVu',
            field=models.CharField(choices=[('Thu ngân', 'Thu ngân'), ('Quản lý', 'Quản lý'), ('Pha chế', 'Pha chế'), ('Phục vụ', 'Phục vụ'), ('Giữ xe', 'Giữ xe')], error_messages={'required': 'Chức vụ không được để trống. Vui lòng nhập thông tin'}, max_length=50, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='DiaChi',
            field=models.CharField(error_messages={'required': 'Địa chỉ không được để trống. Vui lòng nhập thông tin'}, max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='DiaChiLV',
            field=models.CharField(error_messages={'required': 'Địa chỉ làm việc không được để trống. Vui lòng nhập thông tin'}, max_length=255, verbose_name='Địa chỉ làm việc'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='GioiTinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], error_messages={'required': 'Giới tính không được để trống. Vui lòng nhập thông tin'}, max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='HoTen',
            field=models.CharField(error_messages={'required': 'Họ tên không được để trống. Vui lòng nhập thông tin'}, max_length=100, validators=[django.core.validators.RegexValidator(message='Họ tên chỉ được chứa chữ cái và khoảng trắng.', regex='^[a-zA-ZÀ-ỹ\\s]+$')], verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='Ngaysinh',
            field=models.DateField(error_messages={'required': 'Ngày sinh không được để trống. Vui lòng nhập thông tin'}, validators=[pages.employee.models.validate_min_age], verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='SoDienThoai',
            field=models.CharField(error_messages={'required': 'Số điện thoại không được để trống. Vui lòng nhập thông tin', 'unique': 'Số điện thoại này đã tồn tại trong hệ thống.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có 10 chữ số và bắt đầu bằng số 0.', regex='^0\\d{9}$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='TaiKhoanNH',
            field=models.CharField(error_messages={'required': 'Tài khoản ngân hàng không được để trống. Vui lòng nhập thông tin'}, max_length=100, verbose_name='Tài khoản ngân hàng'),
        ),
    ]
