# Generated by Django 6.0.2 on 2026-04-15 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopDongLaoDong',
            fields=[
                ('MaHopDong', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Mã hợp đồng phải bắt đầu bằng 'HD' followed by digits (ví dụ: HD001).", regex='^HD\\d+$')], verbose_name='Mã hợp đồng')),
                ('NgayBatDau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('NgayKetThuc', models.DateField(verbose_name='Ngày kết thúc')),
                ('MucLuong', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Mức lương')),
                ('ChucVu', models.CharField(choices=[('Thu ngân', 'Thu ngân'), ('Quản lý', 'Quản lý'), ('Pha chế', 'Pha chế'), ('Phục vụ', 'Phục vụ'), ('Giữ xe', 'Giữ xe')], max_length=50, verbose_name='Chức vụ')),
                ('LoaiHopDong', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=100, verbose_name='Loại hợp đồng')),
                ('TrangThai', models.CharField(choices=[('Còn hạn', 'Còn hạn'), ('Hết hạn', 'Hết hạn'), ('Sắp đến hạn', 'Sắp đến hạn')], max_length=50, verbose_name='Trạng thái')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hợp đồng lao động',
                'verbose_name_plural': 'Danh sách hợp đồng lao động',
            },
        ),
        migrations.CreateModel(
            name='HopDongLaoDong_CT',
            fields=[
                ('MaHopDong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contract.hopdonglaodong', verbose_name='Mã hợp đồng')),
                ('LuongCoBan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lương cơ bản')),
                ('LuongTheoGio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lương theo giờ')),
                ('CheDoThuong', models.TextField(blank=True, null=True, verbose_name='Chế độ thưởng')),
                ('SoGioLam', models.IntegerField(verbose_name='Số giờ làm')),
                ('GhiChu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Chi tiết hợp đồng lao động',
                'verbose_name_plural': 'Danh sách chi tiết hợp đồng',
            },
        ),
    ]
