# Generated by Django 6.0.2 on 2026-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdonglaodong_ct',
            name='CheDoThuong',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chế độ thưởng'),
        ),
    ]
