# Generated by Django 6.0.3 on 2026-04-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_hopdonglaodong_ct_chedothuong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdonglaodong',
            name='TrangThai',
            field=models.CharField(choices=[('Còn hạn', 'Còn hạn'), ('Hết hạn', 'Hết hạn'), ('Sắp hiệu lực', 'Sắp hiệu lực'), ('Sắp đến hạn', 'Sắp đến hạn')], max_length=50, verbose_name='Trạng thái'),
        ),
    ]
